// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class xhzq233 {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  xhzq233(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  xhzq233.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void init(
    ffi.Pointer<send_fn_t> arg0,
  ) {
    return _init(
      arg0,
    );
  }

  late final _initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<send_fn_t>)>>(
          'init');
  late final _init =
      _initPtr.asFunction<void Function(ffi.Pointer<send_fn_t>)>();
}

class send_data_t extends ffi.Struct {
  @ffi.Char()
  external int type;

  external ffi.Pointer<ffi.Char> str;
}

typedef send_fn_t = ffi.NativeFunction<ffi.Void Function(ffi_send_data)>;
typedef ffi_send_data = ffi.Pointer<send_data_t>;
